version: '3'
services:
  postgres-db:
    build: .
    volumes:
     - ./data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=8aLJab
      - POSTGRES_DB=goDB